# Generated by Django 4.0.4 on 2022-10-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_wish_options_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='library',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.DeleteModel(
            name='Finished',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
