# Generated by Django 4.0.4 on 2022-11-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_finished_options_alter_wish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finished',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
